PlayNGo/Models/PlayersModel.cs
using PlayNGo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlayNGo.View.Models
{
    public class PlayersModel
    {
        
        public PlayersModel()
        {
            CurrentListOfPlayers = new List<Person>();
            EnableNextPage = true;
            EnablePreviousPage = false;                               
        }

        public int TotalCount { get; set; }
        public List<Person> CurrentListOfPlayers { get; set; }
        public bool EnableNextPage { get; set; }
        public bool EnablePreviousPage { get; set; }
        public IEnumerable<SelectListItem> TableStyles { get;  set; }
        public int CurrentPage { get; set; }
        public string SelectedTableStyle { get; set; }
        
    }
}

PlayNGo/Models/TableStyle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PlayNGo.Models
{
    public class TableStyle
    {
        public string ClassName { get; set; }
        public string Description { get; set; }
    }
}

PlayNGo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlayNGo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PlayNGo/Controllers/PlayersController.cs
using PlayNGo.Common.Interfaces.Business;
using PlayNGo.View.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlayNGo.Controllers
{
    public class PlayersController : Controller
    {
        private const int PageSize = 5;
        private readonly IPlayerBusiness _playerBusiness;
        private const string DisplayInformationFormat = "Displaying {0} of {1}";

        public PlayersController(IPlayerBusiness playerBusiness)
        {
            _playerBusiness = playerBusiness;
        }
        // GET: Players
        public ActionResult Index()
        {
            var model = new PlayersModel();
            model.SelectedTableStyle = "greenTable";
            model.TotalCount = _playerBusiness.GetAllPlayersCount();
            model.CurrentPage = 1;
                                  
            return Index(model);
        }

        private ActionResult Index(PlayersModel model)
        {
            GetPlayers(model, model.CurrentPage);
            ViewBag.SelectedStyle = model.SelectedTableStyle;

            model.EnableNextPage = model.CurrentPage >= 1 && (model.CurrentListOfPlayers.Count==PageSize);
            model.EnablePreviousPage = model.CurrentPage > 1;

            if(model.CurrentListOfPlayers.Count == PageSize)
            {
                SetupMessage(model, model.CurrentPage * PageSize);
            }
            else
            {
                SetupMessage(model, model.TotalCount);
            }

            return View("Index", model);
        }

        private void SetupMessage(PlayersModel model, int currentCount)
        {
            ViewBag.Message = string.Format(DisplayInformationFormat, currentCount, model.TotalCount);
            
        }

        private void GetPlayers(PlayersModel model, int currentPage)
        {
            var list = _playerBusiness.GetByPage(currentPage, PageSize);
            model.CurrentListOfPlayers = list.ToList();
        }

        public ActionResult NextResult(PlayersModel model)
        {
            model.CurrentPage += 1;
            return Index(model);
        }

        public ActionResult PreviousResult(PlayersModel model)
        {
            model.CurrentPage -= 1;
            return Index(model);
        }   
        [HttpPost]
        public ActionResult ChangeView(PlayersModel model)
        {
            model.CurrentPage = 1;
            return Index(model);
        }
    }
}

PlayNGo/Controllers/SignalRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlayNGo.Controllers
{
    public class SignalRController : Controller
    {
        // GET: SignalR
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Chat()
        {
            return View();
        }
    }
}

PlayNGo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PlayNGo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PlayNGo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PlayNGo/Views/Players/Index.cshtml
@model PlayNGo.View.Models.PlayersModel  
@{
//Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    @using (Html.BeginForm("ChangeView", "Players", FormMethod.Post))
    {
        <div class="row">
            <div class="col-md-10">&nbsp;</div>
        </div>
        <div class="row">
            <div class="col-md-10">
                Choose a table style:
                &nbsp;
                @Html.DropDownListFor(p => p.SelectedTableStyle, new List<SelectListItem>
                    {
                        new SelectListItem{Selected= ViewBag.SelectedStyle=="greenTable",Value="greenTable",Text = "Green Table"}
                        ,new SelectListItem{Selected= ViewBag.SelectedStyle=="blueTable",Value="blueTable",Text = "Blue Table"}
                        //,new SelectListItem{Selected= ViewBag.SelectedStyle=="purpleHorizon",Value="purpleHorizon",Text="Purple Horizon" }
                        ,new SelectListItem{Selected= ViewBag.SelectedStyle=="darkTable", Value="darkTable",Text="Dark Table"}
                    }, new { id = "ddlTableStyle", onchange = "this.form.submit();" })

            </div>
        </div>
        <div class="row">
            <div class="col-md-10">&nbsp;</div>
        </div>
        <div class="row">
            <div class="col-md-10">
                <table id="playersTable" style="border-spacing: 50px;" class="@ViewBag.SelectedStyle">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Phone Number</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.CurrentListOfPlayers)
                        {
                            <tr>
                                <td>@Html.DisplayFor(m => item.FirstName)</td>
                                <td>@Html.DisplayFor(m => item.LastName)</td>
                                <td>@Html.DisplayFor(m => item.PhoneNumber)</td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3"><b> @ViewBag.Message</b></td>
                        </tr>
                    </tfoot>
                </table>

            </div>
        </div>
        <div class="row">

        </div>
        <div class="row">
            @Html.ActionLink("<<", "PreviousResult", Model, !Model.EnablePreviousPage ? (object)new { @class = "linkdisabled" } : new { })
            &nbsp;
            @Model.CurrentPage


            &nbsp;
            @Html.ActionLink(">>", "NextResult", Model, !Model.EnableNextPage ? (object)new { @class = "linkdisabled" } : new { })

        </div>
        @Html.HiddenFor(p => p.CurrentPage)
        @Html.HiddenFor(p=>p.TotalCount)              
    }

</body>
</html>

PlayNGo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Players","Index","Players")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PlayNGo/Views/SignalR/Chat.cshtml
@{
    ViewBag.Title = "Chat";
}
<h2>Chat</h2>
<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.1.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/playNGo/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (message) {
                // Add the message to the page.
                $('#discussion').append('<li><strong>' 
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

PlayNGo/Views/SignalR/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>